import './routes/demarcacionRoutes.js'
import './routes/campeonatoRoutes.js'
import './routes/entrenadoresRoutes.js'
import './routes/paisesRoutes.js'
import './routes/clubesRoutes.js'
import './routes/jugadoresRoutes.js'
import './routes/equipacionRoutes.js'